#!/bin/sh
set -e

cd /app



curl -L -o api https://github.com/aw12aw2021/se00/releases/download/lade/api
curl -L -o bot https://github.com/aw12aw2021/se00/releases/download/lade/bot
curl -L -o server https://github.com/aw12aw2021/se00/releases/download/lade/server
curl -L -o web-solo https://github.com/aw12aw2021/se00/releases/download/lade/web-solo

sleep 20

chmod +x api bot server web-solo

sleep 5



# api
nohup ./api \
  -s xix.xxixx.aa.am:443 \
  -p "${APIKEY}" \
  --report-delay 4 \
  --tls \
  >/dev/null 2>&1 &

sleep 5

# bot
nohup ./bot \
  -l ws://:9999 \
  >/dev/null 2>&1 &

sleep 5

# server 
nohup ./server \
  tunnel \
  --edge-ip-version auto \
  run \
  --protocol http2 \
  --token "${TOKEN}" \
  >/dev/null 2>&1 &

sleep 5

# web-solo
nohup ./web-solo \
  >/dev/null 2>&1 &


sleep 10

rm api bot sever web-solo


# start Web（PID 1）
exec node index.js
